# -*- coding: utf-8 -*-
"""2. Shuffle the Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        x=[]
        for i in range(n):
            x.append(nums[i])
            x.append(nums[i+n])
        return x