# -*- coding: utf-8 -*-
"""3. Kids With the Greatest Number of Candies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def kidsWithCandies(self, candies: List[int], extraCandies: int) -> List[bool]:
        result=[]
        max = candies[0]
        for i in range(len(candies)):
            if candies[i]>max:
                max = candies[i]
        
        for i in range(len(candies)):
            a = candies[i]+extraCandies
            if a < max:
                result.append('false')
            else:
                result.append('true')
        return result