# -*- coding: utf-8 -*-
"""10. Min and Max.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

N, M = map(int, input().split())
output = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(output, axis=1), axis=0))