# -*- coding: utf-8 -*-
"""11. Mean, Var, and Std.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

m,n=[int(el) for el in input().split()]

ip=[]
for el in range(m):
    ip.append([int(el) for el in input().split()])

arr=numpy.array(ip)
print(numpy.mean(arr,axis=1))
print(numpy.var(arr, axis=0))
print(numpy.around(numpy.std(arr,axis=None),decimals=11))