# -*- coding: utf-8 -*-
"""13. Inner and Outer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

x = numpy.array(input().split(), int)
y = numpy.array(input().split(), int)
print(numpy.inner(x, y), numpy.outer(x, y), sep='\n')