# -*- coding: utf-8 -*-
"""14. Polynomials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

i = [float(x) for x in input().split()]
y = float(input())

print(numpy.polyval(i, y))