# -*- coding: utf-8 -*-
"""15. Linear Algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

ip = int(input())
x = numpy.array([input().split() for _ in range(ip)], float)
print(round(numpy.linalg.det(x),2))