# -*- coding: utf-8 -*-
"""1. Arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def arrays(arr):
    return(numpy.array(arr[::-1], float))