# -*- coding: utf-8 -*-
"""2. Shape and Reshape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy
print(numpy.array(input().split(), int).reshape(3, 3))