# -*- coding: utf-8 -*-
"""4. Concatenate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

P, N, M = map(int,input().split())
X = numpy.array([input().split() for _ in range(P)],int)
Y = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((X, Y), axis = 0))