# -*- coding: utf-8 -*-
"""5. Zeros and Ones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

i = tuple(map(int, input().split()))
print(numpy.zeros(i, int))
print(numpy.ones(i, int))