# -*- coding: utf-8 -*-
"""6. Eye and Identity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))