# -*- coding: utf-8 -*-
"""7. Array Mathematics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

N, M = map(int, input().split())

X = numpy.array([list(map(int, input().split())) for n in range(N)])
Y = numpy.array([list(map(int, input().split())) for n in range(N)])

print(X + Y)
print(X - Y)
print(X * Y)
print(X // Y)
print(X % Y)
print(X ** Y)