# -*- coding: utf-8 -*-
"""8. Floor, Ceil and Rint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy

numpy.set_printoptions(sign=' ')

arr = numpy.array(input().split(),float)

print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))