# -*- coding: utf-8 -*-
"""9. Sum and Prod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import numpy
N, M = map(int, input().split())
X = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(X, axis=0), axis=0))