# -*- coding: utf-8 -*-
"""5. Counting Bits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def countBits(self, n: int) -> List[int]:
        results = [0]
        
        for i in range(1, n+1):
            results.append(results[i & (i-1)] + 1)
            
        return results