# -*- coding: utf-8 -*-
"""1.Say "Hello, World!" With Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

print("Hello, World!")