# -*- coding: utf-8 -*-
"""5. Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

if __name__ == '__main__':
    n = int(input())
    i =0
    for i in range(n):
        print(pow(i, 2))