# -*- coding: utf-8 -*-
"""6. Write a function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def is_leap(year):
    leap = False
    
    if year%4==0 and year%100!=0:
       return True
    elif year%100==0 and year%400==0:
        return True
    else:
        return False
    return leap