# -*- coding: utf-8 -*-
"""7. Print Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

if __name__ == '__main__':
    n = int(input())
    def num(n):
        if n > 0:
            num(n - 1)
            print(n, end = '')
            
    num(n)