# -*- coding: utf-8 -*-
"""2.  Binomial Distribution II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math

nums = 0.12
res = 0
for i in range(0, 3):
    res += math.factorial(10)/math.factorial(i)/math.factorial(10-i) * nums**i * (1-nums)**(10-i)
    if i == 1:
        res1 = 1 - res

print(round(res, 3))
print(round(res1, 3))