# -*- coding: utf-8 -*-
"""3. Normal Distribution I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math

def norm(i, mean, std):
    return 1/2*(1+math.erf((i-mean) / std / 2**(1/2)))

mean = 20
std = 2

print(round(norm(19.5, mean, std), 3))
print(round(norm(22, mean, std) - norm(20, mean, std), 3))