# -*- coding: utf-8 -*-
"""4. Normal Distribution II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math
mean, std = 70, 10
norm = lambda i: 0.5 * (1 + math.erf((i - mean) / (std * (2 ** 0.5))))

print(round((1-norm(80))*100,2))
print(round((1-norm(60))*100,2))
print(round((norm(60))*100,2))