# -*- coding: utf-8 -*-
"""6. The Central Limit Theorem II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math

ticket = float(input())
students = float(input())
total = students * float(input())
x = math.sqrt(students) * float(input())

print(round(0.5*(1+math.erf((ticket - total)/(x * math.sqrt(2)))),4))