# -*- coding: utf-8 -*-
"""7. Pearson Correlation Coefficient I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

ip = int(input())
x = list(map(float,input().strip().split()))
y = list(map(float,input().strip().split()))

avg_x = sum(x) / ip
avg_y = sum(y) / ip

std_x = (sum([(i - avg_x)**2 for i in x]) / ip)**0.5
std_y = (sum([(i - avg_y)**2 for i in y]) / ip)**0.5


covariance = sum([(x[i] - avg_x) * (y[i] -avg_y) for i in range(ip)])

correlation_coefficient = covariance / (ip * std_x * std_y)

print(round(correlation_coefficient,3))