# -*- coding: utf-8 -*-
"""10. Hex Color Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re

ip= int(input())
css = False
for _ in range(ip):
    s = input()
    if '{' in s:
        css = True
    elif '}' in s:
        css = False
    elif css:
        for color in re.findall('#[0-9a-fA-F]{3,6}', s):
            print(color)