# -*- coding: utf-8 -*-
"""14. Validating UID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re
for _ in range(int(input())):
    ip = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', ip)
        assert re.search(r'\d\d\d', ip)
        assert not re.search(r'[^a-zA-Z0-9]', ip)
        assert not re.search(r'(.)\1', ip)
        assert len(ip) == 10
    except:
        print('Invalid')
    else:
        print('Valid')