# -*- coding: utf-8 -*-
"""15. Validating Credit Card Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re
for i in range(int(input())):
    ip = input().strip()
    words = re.search(r'^[456]\d{3}(-?)\d{4}\1\d{4}\1\d{4}$',ip)
    if words:
        processed_words = "".join(words.group(0).split('-'))
        output = re.search(r'(\d)\1{3,}', processed_words)
        if output:
            print('Invalid')
        else :
            print('Valid')
    else:
        print('Invalid')