# -*- coding: utf-8 -*-
"""17. Matrix Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math
import os
import random
import re
import sys

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])
m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

# start   
matrix = list(zip(*matrix))

output = str()

for words in matrix:
    for char in words:
        output += char
       
print(re.sub(r'(?<=\w)([^\w\d]+)(?=\w)', ' ', output))