# -*- coding: utf-8 -*-
"""1. Detect Floating Point Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re

class Main():
    def __init__(self):
        self.x = int(input())
        
        for i in range(self.x):
            self.y = input()
            print(bool(re.match(r'^[-+]?[0-9]*\.[0-9]+$', self.y)))
                    
if __name__ == '__main__':
    out = Main()