# -*- coding: utf-8 -*-
"""2. Re.split().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

regex_pattern = r"[.,]+"
import re
print("\n".join(re.split(regex_pattern, input())))