# -*- coding: utf-8 -*-
"""3. Group(), Groups() & Groupdict().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re

pattern=r"([a-zA-Z0-9])\1+"

x = re.search(pattern,input())

if x:
    print(x.group(1))
else:
    print(-1)