# -*- coding: utf-8 -*-
"""7. Validating Roman Numerals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

thousands = 'M{0,3}'
hundreds = '(C[MD]|D?C{0,3})'
ten = '(X[CL]|L?X{0,3})'
nums = '(I[VX]|V?I{0,3})'
regex_pattern = r"%s%s%s%s$" % (thousands, hundreds, ten, nums) # Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))