# -*- coding: utf-8 -*-
"""8. Validating phone numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import re

x = int(input())

for i in range(x):
    nums = input()
    if(len(nums)==10 and nums.isdigit()):
        output = re.findall(r"^[789]\d{9}$",nums)
        if(len(output)==1):
            print("YES")
        else:
            print("NO")
    else:
        print("NO")

