# -*- coding: utf-8 -*-
"""2. Sort Integers by The Number of 1 Bits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def sortByBits(self, arr: List[int]) -> List[int]:
        x=[]
        for i in sorted(arr):
            x.append((i,bin(i).count('1')))
            j = sorted(x, key=lambda i: i[1])
        arr1=[]
        for i in j:
            arr1.append(i[0])
        return arr1