# -*- coding: utf-8 -*-
"""10. String Formatting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def print_formatted(number):
    len_num = len(bin(number)[2:])
   
    for i in range(1,number+1):
        print(str(i).rjust(len_num,' '),end=" ")
        print(oct(i)[2:].rjust(len_num,' '),end=" ")
        print(((hex(i)[2:]).upper()).rjust(len_num,' '),end=" ")
        print(bin(i)[2:].rjust(len_num,' '),end=" ")
        print("")