# -*- coding: utf-8 -*-
"""9. Alphabet Rangoli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def print_rangoli(size):
    import string
    pattern = string.ascii_lowercase
    arr = []
    for i in range(n):
        x = "-".join(pattern[i:n])
        arr.append((x[::-1]+x[1:]).center(4*n-3, "-"))
        
    print('\n'.join(arr[:0:-1]+arr))

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)