# -*- coding: utf-8 -*-
"""11. The Minion Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def minion_game(string):
    player1 = 0;
    player2 = 0;
    len_1 = len(string)
    for i in range(len_1 ):
        if s[i] in "AEIOU":
            player1 += (len_1 )-i
        else :
            player2 += (len_1 )-i
    
    if player1 > player2:
        print("Kevin", player1)
    elif player1 < player2:
        print("Stuart",player2)
    elif player1 == player2:
        print("Draw")
    else :
        print("Draw")