# -*- coding: utf-8 -*-
"""12. Merge the Tools!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

from collections import OrderedDict
def merge_the_tools(string, k):
    len_str = len(string)
    for i in range(0,len_str,k):
        print(''.join(OrderedDict.fromkeys(string[i:i + k])))