# -*- coding: utf-8 -*-
"""1. sWAP cASE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def swap_case(s):
    result = '';
    for char in s:
        if(char.isupper()==True):
            result += (char.lower());
        elif(char.islower()==True):
            result += (char.upper());
        else:
            result += char;
    return result