# -*- coding: utf-8 -*-
"""2. String Split and Join.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def split_and_join(line):
    result = line.split();
    result = "-".join(result)
    return result