# -*- coding: utf-8 -*-
"""3. What's Your Name?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def print_full_name(first, last):
    print("Hello {} {}! You just delved into python.".format(first,last))