# -*- coding: utf-8 -*-
"""3. Mutations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def mutate_string(string, position, character):
    x = position+1
    result = string[:position]+character+string[x:]
    return result