# -*- coding: utf-8 -*-
"""6. Text Wrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def wrap(string, max_width):
    return textwrap.fill(string,max_width)