# -*- coding: utf-8 -*-
"""1. Polar Coordinates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import cmath;

num = complex(input())
x = complex(num)

print(cmath.polar(x)[0])
print(cmath.polar(x)[1])