# -*- coding: utf-8 -*-
"""2. Find Angle MBC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

import math
x = int(input())
y = int(input())
cal = math.sqrt(x**2+y**2)
theta = math.acos(y/cal )
print(str(round(math.degrees(theta)))+'°')