# -*- coding: utf-8 -*-
"""4. Mod Divmod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

x = int(input());
y = int(input());
print(x//y);
print(x%y);
print(divmod(x,y));