# -*- coding: utf-8 -*-
"""5. Power - Mod Power.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

x = int(input())
y = int(input())
i = int(input())

print(pow(x,y))

print(pow(x,y,i))