# -*- coding: utf-8 -*-
"""6. Integers Come In All Sizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

x = int(input())
y = int(input())
m = int(input())
n = int(input())

print((x**y)+(m**n))