# -*- coding: utf-8 -*-
"""10. Set .add().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

n = int(input())
states = set()

for i in range(n):
    states.add(input())

print(len(states))