# -*- coding: utf-8 -*-
"""12. Set .union() Operation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

n = int(input())
input1 = set(input().split());

n1 = int(input())
input2 = set(input().split());

input3 = input1.union(input2)

print(len(input3))