# -*- coding: utf-8 -*-
"""15. Set Mutations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

len_ip = int(input())

input1 = set(map(int, input().split()))

out_len = int(input())

for i in range(out_len):
    nums = input().split()
    if nums[0] == 'intersection_update':
        temp_input = set(map(int, input().split()))
        input1.intersection_update(temp_input)
    elif nums[0] == 'update':
        temp_input = set(map(int, input().split()))
        input1.update(temp_input)
    elif nums[0] == 'symmetric_difference_update':
        temp_input = set(map(int, input().split()))
        input1.symmetric_difference_update(temp_input)
    elif nums[0] == 'difference_update':
        temp_input = set(map(int, input().split()))
        input1.difference_update(temp_input)
    else :
        assert False

print(sum(input1))