# -*- coding: utf-8 -*-
"""16. The Captain's Room.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

n = int(input())

input1 = map(int, input().split())
input1 = sorted(input1)

for i in range(len(input1)):
    if(i != len(input1)-1):
        if(input1[i]!=input1[i-1] and input1[i]!=input1[i+1]):
            print(input1[i])
            break;
    else:
        print(input1[i])