# -*- coding: utf-8 -*-
"""17. Check Subset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

n = int(input())

for _ in range(n):
    x = input()
    X = set(input().split())
    y = int(input())
    Y = set(input().split())
    print(X.issubset(Y))