# -*- coding: utf-8 -*-
"""18. Check Strict Superset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def isstrictsuperset(x,y):
    return y.issubset(x) and not(x.issubset(y))

x = set(int(a) for a in input().split(' '))
n = int(input())
res = True

for _ in range(n):
    y = set(int(a) for a in input().split(' '))
    res &= isstrictsuperset(x,y)
    
print(res)