# -*- coding: utf-8 -*-
"""19. Set .difference() Operation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

n = int(input())
set1 = set(map(int,input().split()))
n1 = int(input())
set2 = set(map(int,input().split()))
print(len(set1-set2))