# -*- coding: utf-8 -*-
"""3. Nested Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

if __name__ == '__main__':
    pupils=[]
    for _ in range(int(input())):
        name = input()
        score = float(input())
        pupils.append([name,score]) 
    
    a = 99999
    for i in range(len(pupils)):
        if a > float(pupils[i][1]):
            a = float(pupils[i][1])
    
    b=999999
    for i in range(len(pupils)):
        if float(pupils[i][1]) > float(a) and b > float(pupils[i][1]):
            b = float(pupils[i][1])
            
    runner_up = []
    for i in range(len(pupils)):
        if float(pupils[i][1]) == float(b):
            runner_up.append(pupils[i][0])
    runner_up = sorted(runner_up)
    
    for i in range(len(runner_up)):
        print(runner_up[i])