# -*- coding: utf-8 -*-
"""7. Introduction to Sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

def average(array):
    total = sum(set(array))
    len_total = len(set(array))
    avg = total/len_total
    return avg