# -*- coding: utf-8 -*-
"""3.  Single Number II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def singleNumber(self, nums: List[int]) -> int:
        out = int((3*sum(set(nums))-sum(nums))/2)
        return out