# -*- coding: utf-8 -*-
"""1. Defanging an IP Address.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def defangIPaddr(self, address: str) -> str:
        ip=address.replace(".","[.]")
        return ip