# -*- coding: utf-8 -*-
"""2. Find Numbers with Even Number of Digits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def findNumbers(self, nums: List[int]) -> int:
        res = 0
        for n in nums:
            tmp = 0
            while n > 0:
                tmp += 1
                n //= 10
            if tmp % 2 == 0:
                res += 1
        return res