# -*- coding: utf-8 -*-
"""3. Number of Good Pairs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        x={}
        init=0
        for i in nums:
            if not i in x:
                x[i]=0
            x[i]+=1
        
        for i in x:
            n=x[i]
            init+=(n*(n-1)//2)
            
        return init