# -*- coding: utf-8 -*-
"""5. Subtract the Product and Sum of Digits of an Integer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def subtractProductAndSum(self, n: int) -> int:
        product = 1
        sum = 0
        for i in str(n):
            product *= int(i)
            sum += int(i)
        return product - sum