# -*- coding: utf-8 -*-
"""6. XOR Operation in an Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkGasLexoUEUCTx-NSowY9Rg8pbef81o
"""

class Solution:
    def xorOperation(self, n: int, start: int) -> int:
        init=0
        for i in range(n):
            init^=(start+i*2)
        
        return init